<br style="clear: both;" />

<div style="float: left;">
	<span class="badge badge_<?php echo $_GET['action']; ?>"><?php echo $_GET['action']; ?></span>
</div>

<div style="float: left;">
	<strong style="display: inline-block; font-size: 14px; padding-top: 5px;" class="text_<?php echo $_GET['action']; ?>"><?php echo $RAML->baseUri . $RAML->currentResource->path; ?></strong>
</div>

<br style="clear: both;" />

<p style="margin-top: 30px;"><?php echo $RAML->currentResource->verbs[$_GET['action']]['description']; ?></p>

<h3>Parameters</h3>

<h3>Response</h3>

<h3>Other Endpoint Actions</h3>
<?php
foreach ($RAML->currentResource->verbs as $verb => $resource) {
	if ($verb == $_GET['action']) {
		continue;
	}
?>

<div style="float: left;">
	<a href="<?php echo $_SERVER['PHP_SELF']; ?>?path=<?php echo $RAML->currentResource->path; ?>&action=<?php echo $verb; ?>" class="badge badge_<?php echo $verb; ?>"><?php echo $verb; ?></a>
</div>

<?php } ?>
