<br style="clear: both;" />

<div style="float: left;">
	<span class="badge badge_<?php echo $RAML->currentAction; ?>"><?php echo $RAML->currentAction; ?></span>
</div>

<div style="float: left;">
	<strong style="display: inline-block; font-size: 14px; padding-top: 5px;" class="text_<?php echo $RAML->currentAction; ?>"><?php echo $RAML->baseUri . $RAML->currentResource->path; ?></strong>
</div>

<br style="clear: both;" />

<p style="margin-top: 30px;"><?php echo $RAML->currentResource->verbs[$RAML->currentAction]['description']; ?></p>


<?php if ($RAML->currentResource->verbs[$RAML->currentAction]['queryParameters']): ?>
	<h3>Query Parameters</h3>
	<table>
		<thead>
			<tr>
				<td>Parameter</td><td>Type</td><td>Description</td>
			</tr>
		</thead>
		
		<?php
		foreach ($RAML->currentResource->verbs[$RAML->currentAction]['queryParameters'] as $param => $details) {
		?>
		
			<tr>
				<td><?php echo $param; ?></td><td><?php echo $details['type']; ?></td><td><?php echo $details['description']; ?></td>
			</tr>
			
		<?php } ?>
		
	</table>
<?php endif; ?>


<?php if ($RAML->currentResource->verbs[$RAML->currentAction]['body']['application/x-www-form-urlencoded']['formParameters']): ?>
<h3>Form Parameters</h3>
<table>
	<thead>
		<tr>
			<td>Parameter</td><td>Type</td><td>Description</td>
		</tr>
	</thead>
	
	<?php
	foreach ($RAML->currentResource->verbs[$RAML->currentAction]['body']['application/x-www-form-urlencoded']['formParameters'] as $param => $details) {
	?>
	
		<tr>
			<td><?php echo $param; ?></td><td><?php echo $details['type']; ?></td><td><?php echo $details['description']; ?></td>
		</tr>
		
	<?php } ?>
	
</table>
<?php endif; ?>



<h3>Response</h3>
<?php
foreach ($RAML->currentResource->verbs[$RAML->currentAction]['responses'] as $code => $response) {
?>
	<strong><?php echo $code; ?>:</strong>
	<div class="apiresponse">
			<?php echo formatResponse($response['body']['example']); ?>
	</div>
<?php
}
?>

<?php if (count($RAML->currentResource->verbs) > 1): ?>
	<h3>Other Endpoint Actions</h3>
	<?php
	foreach ($RAML->currentResource->verbs as $verb => $resource) {
		if ($verb == $RAML->currentAction) {
			continue;
		}
	?>
	<div style="float: left;">
		<a href="<?php echo $_SERVER['PHP_SELF']; ?>?path=<?php echo $RAML->currentResource->path; ?>&action=<?php echo $verb; ?>" class="badge badge_<?php echo $verb; ?>"><?php echo $verb; ?></a>
	</div>
	
	<?php } ?>
<?php endif; ?>