<h3>Available Endpoints</h3>
<ul class="resources">
	<?php foreach ($RAML->path()->getChildren() as $abspath => $endpoint) { ?> 
	<li>
		<div style="float: left; width: 150px;">
			<a href="<?php echo $_SERVER['PHP_SELF']; ?>?path=<?php echo $abspath; ?>"><?php echo $endpoint; ?></a>
		</div>
		
		<div style="float: left;">
			<?php echo $RAML->getPathObject($abspath)->get('description'); ?>
		</div>
		
		<br style="clear: both;" />
	</li>
	<?php } ?>
</ul>