<h3>Available Actions</h3>

<ul class="verbs">
	<?php foreach ($RAML->currentResource->verbs as $verb => $resource) { ?>
	<li>
		<div style="float: left;">
			<a href="<?php echo $_SERVER['PHP_SELF']; ?>?path=<?php echo $RAML->currentResource->path; ?>&action=<?php echo $verb; ?>" class="badge badge_<?php echo $verb; ?>"><?php echo $verb; ?></a>
		</div>
		
		<div style="float: left;">
			<?php echo $resource['description']; ?>
		</div>
		<br style="clear: both;" />
	</li>
	<?php } ?>
</ul>