<html>
	<head>
		<title><?php echo $RAML->title; ?>: <?php echo $RAML->currentResource->path; ?></title>
		
		<style type="text/css">
			body, table {
				margin: 0;
				font-family: arial;
				font-size: 12px;
			}
			
			a { 
				text-decoration: none;
			}
			
			h3 {
				margin-top: 40px;
			}
			
			header {
				padding: 10px 20px;
				background: #333;
				color: #fff;
				border-bottom: 2px solid #999;
			}
			
			header a {
				color: #fff;
			}
			
			article {
				float: left;
				width: 600px;
				margin: 0 20px;
			}
			
			nav {
				float: right;
				min-width: 200px;
				border-left: 1px dashed #999;
				padding: 0 15px;
			}
			
			footer {
				clear: both;
				padding: 80px 0 20px 0;
				text-align: center;
				font-size: 10px;
			}
			
			table thead tr td {
				background: #666;
				color: #fff;
				font-weight: bold;
			}
			
			table tr {
				padding: 15px 0;
			}
			
			tr:nth-child(odd) {
			    background-color: #f3f3f3;
			}
			
			table td {
				vertical-align: top;
				padding: 5px;
			}
			
			.badge {
				display: inline-block;
				font-size: 14px;
				padding: 5px;
				margin-right: 20px;
		        border-radius: 0;
		        text-transform: uppercase;
		        width: 70px;
		        font-weight: normal;
		        color: #f3f3f6;
		        line-height: normal;
		        background-color: #999;
		        text-align: center;
		    }
		    .block.collapsed .badge {
		        visibility: visible;
		    }
		    .badge_get {
		        background-color: #63a8e2;
		    }
		    .badge_post {
		        background-color: #6cbd7d;
		    }
		    .badge_put {
		        background-color: #22bac4;
		    }
		    .badge_patch {
		    	background-color: #02b0e2;
		    }
		    .badge_delete {
		        background-color: #d26460;
		    }
		    .badge_connect {
		    	background-color: #e48f0a;
		    }
		    .badge_trace {
		    	background-color: #98b805;
		    }
		    
		    .text_get {
		        color: #0b88b9;
		    }
		    .text_post {
		        color: #6cbd7d;
		    }
		    .text_put {
		        color: #22bac4;
		    }
		    .text_patch {
		    	color: #02b0e2;
		    }
		    .text_delete {
		        color: #d26460;
		    }
		    .text_connect {
		    	color: #e48f0a;
		    }
		    .text_trace {
		    	color: #98b805;
		    }
		    
		    
		    ul.verbs, ul.resources, nav ul {
		    	margin: 0;
		    	padding: 0;
		    	list-style-type: none;
		    }
		    
		    ul.verbs li, ul.resources li {
		    	padding: 0 0 10px 0;
		    	margin: 0 0 10px 0;
		    	border-bottom: 1px dotted #ccc;
		    }
		    
		    ul.resources li a {
		    	font-weight: bold;
		    	font-size: 16px;
		    	color: #666;
		    }
		    
		    ul.resources li a:hover {
		    	color: #63a8e2;
		    }
		    
		    nav ul li a {
		    	display: block;
		    	padding: 0 0 10px 0;
		    	margin: 0 0 10px 0;
		    	border-bottom: 1px dotted #ccc;
		    	font-size: 14px;
		    	color: #666;
		    }
		    
		    nav ul li a:hover {
		    	font-weight: bold;
		    }
		    
		    div.apiresponse {
		    	width: 600px;
		    	max-height: 300px;
		    	background: #f3f3f3;
		    	border: 1px solid #333;
		    	padding: 10px;
		    	overflow: scroll;
		    	font-family: monospace;
		    	font-size: 10px;
		    }
		    
		    
		</style>
		
	</head>

	<body>
		<header>
			<h1><a href="<?php echo $_SERVER['PHP_SELF']; ?>"><?php echo $RAML->title; ?></a></h1>
			<p>version <?php echo $RAML->version; ?> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <?php echo $RAML->baseUri; ?></p>
		</header>
		
		
		<article>
		
			<?php if ($RAML->currentResource->path != '/'): ?>
				<h2><?php echo $RAML->currentResource->path; ?></h2>
			<?php endif; ?>
			
			
			
			<?php if(empty($_GET['action'])):
				echo $RAML->currentResource->description; 
			endif; ?>
			
			
			<?php
			if (!$RAML->currentResource->exists && !$RAML->currentAction):
				include('_404.phtml');
			endif;
			?>
			
			
			<?php 
			if ($RAML->currentResource->verbs && !$RAML->currentAction):
				include('_verbs.phtml');
			endif;
			?>
			
			
			
			<?php 
			if ($RAML->currentResource->resources && !$RAML->currentAction):
				include('_resources.phtml');
			endif;
			?>
			
			
			<?php
			if ($RAML->currentAction):
				include('_action.phtml');
			endif;
			?>
			
		
		</article>
			
			
		<nav>
			<?php 
			if ($RAML->resources): 
				include('_menu.phtml');
			endif; 
			?>
		</nav>


		<footer>
			
		</footer>
	</body>
</html>